config/routes.rb
HoopMan::Application.routes.draw do
  root 'welcome#index'
  
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  namespace :api do
    get '/inventory/trips' => 'trips#inventory'
    get '/inventory/light/trips' => 'trips#inventory', defaults: { publishing_mode: :lite }
    get '/inventory/staging/trips' => 'trips#inventory', defaults: { publishing_mode: :staging }
    
    get '/trips/:id' => 'trips#show'
    
    get '/inventory/images' => 'images#inventory'
    get '/inventory/trashes' => 'trashes#inventory'
  end

  get '/trips-admin' => 'admin/trips#index'
  get '/trips-admin/:id' => 'admin/trips#show', as: 'trips_admin'
  put '/trips-admin/:id' => 'admin/trips#update', as: 'trips_admin_update'
  get '/trips-admin/:id/edit' => 'admin/trips#edit', as: 'trips_admin_edit'
  get '/trips-admin/:id/duplicate' => 'admin/trips#duplicate', as: 'duplicate_trips_admin'
  delete '/trips-admin/:id' => 'admin/trips#destroy', as: 'delete_trips_admin'
  delete '/trips-admin/:id/hard_destroy' => 'admin/trips#hard_destroy', as: 'delete_hard_trips_admin'
  
  put '/users-admin/:id' => 'admin/users#update', as: 'users_admin_update'
  put '/images-admin/:id' => 'admin/images#update', as: 'images_admin_update'

  # Routes for paths
  put '/paths-admin/:id' => 'admin/paths#update', as: 'paths_admin_update'
  post '/paths-admin' => 'admin/paths#create', as: 'paths_admin'
  delete '/paths-admin/:id' => 'admin/paths#destroy', as: 'paths_admin_delete'
  
  # Routes for path-trips
  delete '/path_trips-admin/:path_id/:trip_id' => 'admin/path_trips#destroy', as: 'path_trips_admin_delete'
  post '/path_trips-admin/:path_id/:trip_id' => 'admin/path_trips#create', as: 'path_trips_admin'
  
  # Routes for pois
  get '/pois-admin/:id' => 'admin/pois#show', as: 'pois_admin'
  put '/pois-admin/:id' => 'admin/pois#update', as: 'pois_admin_update'
  delete '/pois-admin/:id' => 'admin/pois#destroy', as: 'pois_admin_delete'
  
  # Routes for poi-trips
  delete '/poi_trips-admin/:poi_id/:trip_id' => 'admin/poi_trips#destroy', as: 'poi_trips_admin_delete'
  post '/poi_trips-admin/:poi_id/:trip_id' => 'admin/poi_trips#create', as: 'poi_trips_admin'

  # Routes for contents
  post '/contents-admin' => 'admin/contents#create', as: 'contents_admin'
  delete '/contents-admin/:id' => 'admin/contents#destroy', as: 'contents_admin_delete'
  put '/contents-admin/:id' => 'admin/contents#update', as: 'contents_admin_update'
end

app/models/poi.rb
#encoding: utf-8
class Poi < ActiveRecord::Base
  has_and_belongs_to_many :trips, class_name: "Trip", join_table: :poi_trips
  
  belongs_to :poi_category
  belongs_to :poi_kind
  belongs_to :image
  
  has_many :contents, as: :contentable, inverse_of: :contentable, dependent: :destroy
  has_many :slides, dependent: :destroy
  
  attr_accessor :lat, :lon
  before_validation :update_coordinates
  after_save :update_trips
  
  validates :poi_kind, :title, :mode, :lat, :lon, presence: true
  validates :details, presence: true, :if => Proc.new { |poi| poi.is_slide_based? }
  
  validates :image, presence: true, :unless => Proc.new { |poi| poi.is_small? }
  
  scope :staged_trip, -> { joins(:trips).distinct('poi_trips.trip_id').where('trips.staging = TRUE') }
  scope :staged_poi, -> { where(staging: true) }
  
  rails_admin do         
    edit do
      include_all_fields
      exclude_fields :created_at, :updated_at, :checksum
      field :lat
      field :lon
    end
    
    list do
      scopes [:staged_trip, :staged_poi, nil]
      field :id
      field :lang
      field :title
      field :listed_on_trips
      field :listed
      field :staging
    end
  end
  
  def duplicate_with_children_and_save
    new_poi=self.dup
    new_poi.save
    
    self.contents.each do |content|
      new_content=content.dup
      new_content.contentable_id = new_poi.id
      new_content.save
    end
    
    self.slides.each do |slide|
      new_slide=slide.dup
      new_slide.poi_id = new_poi.id
      new_slide.save
    end
    
    new_poi
  end
  
  def listed_on_trips
    trip_list = String.new
    trips.each do |trip|
      trip_list << "#{trip.full_name}, "
    end
    trip_list.chop.chop
  end
  
  def lang
    return nil if trips.empty?
    trips.first.lang
  end
  
  def is_small?
    self.mode == "small"
  end
  
  def is_slide_based?
    self.mode == "slide_based"
  end
  
  def mode_enum
    Poi.modes.map { |element| element[1] }
  end
  
  def lat
    return @lat unless @lat.nil?
    coordinates.lat unless coordinates.nil?
  end
  
  def lon
    return @lon unless @lon.nil?
    coordinates.lon unless coordinates.nil?
  end
  
  def update_trips
    trips.each do |trip|
      trip.update_checksum && trip.save
    end
  end
  
  def self.modes
    [["A modo de slides (Requiere descripción)", "slide_based"], ["Pequeño", "small"], ["Normal", "normal"]]
  end
  
  protected
  
  def update_coordinates
    self.coordinates = "POINT(#{self.lon.to_f} #{self.lat.to_f})"
  end
  

end

app/controllers/admin/pois_controller.rb
class Admin::PoisController < ApplicationController
  layout 'admin'

  before_filter :authenticate_user!
  before_filter :find_poi, only: [:update, :destroy, :show]

  def update
    if @poi.update_attributes(poi_params)
      flash[:notice] = I18n.t('pois.update.success')
    else
      flash[:alert] = I18n.t('pois.update.failure')
    end

    redirect_to pois_admin_path(params[:id])
  end

  def create
    @poi = Poi.create(poi_params)
    if @poi.save
      PoiTrip.create(poi_id: @poi.id, trip_id: params[:poi][:trip_id])
      flash[:notice] = I18n.t('pois.create.success')
    else
      flash[:alert] = I18n.t('pois.create.failure')
    end
    
    redirect_to trips_admin_path(params[:poi][:trip_id])
  end

  def destroy
    if @poi.destroy
      flash[:notice] = I18n.t('pois.destroy.success')
    else
      flash[:alert] = I18n.t('pois.destroy.failure')
    end
    redirect_to :back
  end
  
  def show
    @poi_main_images = Image.where(image_type: 'photo')
    @poi_kinds = PoiKind.all
    @poi_modes = Poi.modes
    @poi_categories = PoiCategory.all
  end

  protected

  def find_poi
    @poi = Poi.find(params[:id])
  end

  def poi_params
     params[:poi].permit(:title, :lat, :lon, :details, :listed, :sponsored, :published, :published_on_lite_version, :poi_kind_id, :poi_category_id, :mode, :image)
  end
end

app/views/admin/pois/_list.html.erb
<ul class="actions">
	<li><b>Puntos de interés</b></li>
	<li><%= link_to 'Nuevo', '/admin/poi/new', target: '_blank', :class => "highlighted" %></li> 
</ul>

<div class="table">
	<div class="section">POIs no asignados a este recorrido (<%= @trip_unassigned_pois.count %>)</div>
	<% @trip_unassigned_pois.each do |poi| %>
		<%= render partial: 'admin/pois/poi', object: poi, locals: { assignable: true } %>
	<% end %>
	<div class="highlighted">
		<div class="section highlighted">POIs asignados a este recorrido (<%= @trip_assigned_pois.count %>)</div>
		<% @trip_assigned_pois.each do |poi| %>
			<%= render partial: 'admin/pois/poi', object: poi, locals: { assignable: false } %>
		<% end %>
	</div>
</div>

app/views/admin/pois/_poi.html.erb
<div class="row poi hoverable">
	<p class="title">
		<%= poi.title %> - <span class="kind"><%= poi.poi_kind.keyword %></span> - 
		<span class="lang"><%= poi.poi_kind.lang %></span>
	</p>
	<p class="actions">
		<% if assignable %>
			<%= link_to 'Ligar', poi_trips_admin_path(poi, @trip.id), :method => :post %> 
		<% else %>
			<%= link_to 'Desligar', poi_trips_admin_delete_path(poi, @trip.id), :method => :delete %> 
		<% end %>
		<%= link_to 'Editar', pois_admin_path(poi) %> 
		<%= link_to 'Eliminar', pois_admin_delete_path(poi), :method => :delete, :confirm => "¿Deseas eliminar este recorrido?" %> 
		<span class="status"><%= poi.published ? 'Publicado' : 'Sin publicar' %> </span>
	</p>
</div>

app/views/admin/pois/show.html.erb
<%= render partial: 'admin/shared/notifications' %>
<div class="centered">
	<h2>Detalles del Punto de interés</h2>
</div>

<div class="card">
	<ul class="actions">
		<li><%= link_to 'Atrás', :back %></li>
	</ul>
	
	<div class="header">
		<div class="title">
			<h3 id="title-field" class="hoverable edit-field" data-form="title"><%= @poi.title %></h3> 
			<%= render 'admin/pois/fields/title' %>
		</div>
	</div>
	
	<div class="sub-header">
		<div id="map" class="for-poi"></div>
		<div class="coordinates">
			<div class="toggler">
				<%= link_to 'Editar coordenadas', 'javascript:void(0)', :class => 'edit-field', id: 'coordinates-field', 'data-form' => 'coordinates' %>
			</div>
			<%= render 'admin/pois/fields/coordinates' %>
		</div>
	</div>
	
	<div id="details-field" class="details hoverable edit-field" data-form="details"><%= @poi.details.blank? ? "Sin detalles" : @poi.details %></div>
	<%= render 'admin/pois/fields/details' %>

	<div class="table">
		<div class="section">Características</div>
		<div id="listed-field" class="row hoverable edit-field" data-form="listed">
			<div class="section-title">¿Listado en la portada del recorrido?</div>
			<div class="section-details"><%= @poi.listed ? "Si" : "No" %></div>
		</div>
		<%= render 'admin/pois/fields/listed' %>
		
		<div id="sponsored-field" class="row hoverable edit-field" data-form="sponsored">
			<div class="section-title">¿POI Patrocinado?</div>
			<div class="section-details"><%= @poi.sponsored ? "Si" : "No" %></div>
		</div>
		<%= render 'admin/pois/fields/sponsored' %>
		
		<div id="published-field" class="row hoverable edit-field" data-form="published">
			<div class="section-title">¿Ya está publicado?</div>
			<div class="section-details"><%= @poi.published ? "Si" : "No" %></div>
		</div>
		<%= render 'admin/pois/fields/published' %>
		
		<div id="published-on-lite-version-field" class="row hoverable edit-field" data-form="published-on-lite-version">
			<div class="section-title">¿Publicado en la versión light?</div>
			<div class="section-details"><%= @poi.published_on_lite_version ? "Si" : "No" %></div>
		</div>
		<%= render 'admin/pois/fields/published_on_lite_version' %>
		<br/>
		<div id="poi-kind-field" class="row hoverable edit-field" data-form="poi-kind">
			<div class="section-title">Tipo del POI</div>
			<div class="section-details"><%= @poi.poi_kind.nil? ? "Sin tipo" : @poi.poi_kind.full_name %></div>
		</div>
		<%= render 'admin/pois/fields/poi_kind' %>
		<div id="mode-field" class="row hoverable edit-field" data-form="mode">
			<div class="section-title">Estilo de POI</div>
			<div class="section-details"><%= @poi.mode %></div>
		</div>
		<%= render 'admin/pois/fields/mode' %>
		<div id="poi-category-field" class="row hoverable edit-field" data-form="poi-category">
			<div class="section-title">Categoría de Arte del POI</div>
			<div class="section-details"><%= @poi.poi_category.nil? ? "Sin categoría" : @poi.poi_category.full_name %></div>
		</div>
		<%= render 'admin/pois/fields/poi_category' %>
		<br/>
		
		<div id="main-image-field" class="row hoverable edit-field" data-form="main-image">
			<div class="section-title">Imagen de Portada</div>
			<div class="section-details"><%= @poi.image.nil? ? "Sin imagen" : @poi.image.name  %></div>
		</div>
		<%= render 'admin/pois/fields/main_image' %>
	</div>
	
	
</div>