config/routes.rb
HoopMan::Application.routes.draw do
  root 'welcome#index'
  
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  namespace :api do
    get '/inventory/trips' => 'trips#inventory'
    get '/inventory/light/trips' => 'trips#inventory', defaults: { publishing_mode: :lite }
    get '/inventory/staging/trips' => 'trips#inventory', defaults: { publishing_mode: :staging }
    
    get '/trips/:id' => 'trips#show'
    
    get '/inventory/images' => 'images#inventory'
    get '/inventory/trashes' => 'trashes#inventory'
  end

  get '/trips-admin' => 'admin/trips#index'
  get '/trips-admin/:id' => 'admin/trips#show', as: 'trips_admin'
  put '/trips-admin/:id' => 'admin/trips#update', as: 'trips_admin_update'
  get '/trips-admin/:id/edit' => 'admin/trips#edit', as: 'trips_admin_edit'
  get '/trips-admin/:id/duplicate' => 'admin/trips#duplicate', as: 'duplicate_trips_admin'
  delete '/trips-admin/:id' => 'admin/trips#destroy', as: 'delete_trips_admin'
  delete '/trips-admin/:id/hard_destroy' => 'admin/trips#hard_destroy', as: 'delete_hard_trips_admin'
  
  put '/users-admin/:id' => 'admin/users#update', as: 'users_admin_update'
  put '/images-admin/:id' => 'admin/images#update', as: 'images_admin_update'

  # Routes for paths
  put '/paths-admin/:id' => 'admin/paths#update', as: 'paths_admin_update'
  post '/paths-admin' => 'admin/paths#create', as: 'paths_admin'
  delete '/paths-admin/:id' => 'admin/paths#destroy', as: 'paths_admin_delete'
  
  # Routes for path-trips
  delete '/path_trips-admin/:path_id/:trip_id' => 'admin/path_trips#destroy', as: 'path_trips_admin_delete'
  post '/path_trips-admin/:path_id/:trip_id' => 'admin/path_trips#create', as: 'path_trips_admin'
  
  # Routes for pois
  get '/pois-admin/:id' => 'admin/pois#show', as: 'pois_admin'
  put '/pois-admin/:id' => 'admin/pois#update', as: 'pois_admin_update'
  delete '/pois-admin/:id' => 'admin/pois#destroy', as: 'pois_admin_delete'
  
  # Routes for poi-trips
  delete '/poi_trips-admin/:poi_id/:trip_id' => 'admin/poi_trips#destroy', as: 'poi_trips_admin_delete'
  post '/poi_trips-admin/:poi_id/:trip_id' => 'admin/poi_trips#create', as: 'poi_trips_admin'

  # Routes for contents
  post '/contents-admin' => 'admin/contents#create', as: 'contents_admin'
  delete '/contents-admin/:id' => 'admin/contents#destroy', as: 'contents_admin_delete'
  put '/contents-admin/:id' => 'admin/contents#update', as: 'contents_admin_update'
end

app/models/path.rb
class Path < ActiveRecord::Base
  has_and_belongs_to_many :trips, class_name: "Trip", join_table: :path_trips
  
  after_save :update_trip_checksum
  
  before_save :transform_coordinates
  
  #before_destroy { PathTrip.where(path_id: id).destroy_all }
  scope :staged_trip, -> { joins(:trips).distinct('path_trips.trip_id').where('trips.staging = TRUE') }
  
  rails_admin do         
    list do
      scopes [:staged_trip]
      field :id
      field :name
      field :listed_on_trips
      field :trip_name
    end
  end
  
  def listed_on_trips
    return nil if trips.empty? 
    trip_list = String.new
    trips.each do |trip|
      trip_list << "#{trip.full_name}, "
    end
    trip_list.chop.chop
  end
  
  def trip_name
    return nil if trips.empty? 
    return nil if trips.first.trip_resource.nil?
    trips.first.trip_resource.identifier
  end
  
  protected 
  def update_trip_checksum
    trips.each do |trip|
      trip.update_checksum && trip.save
    end
  end
  
  def transform_coordinates
    if self.coordinates_vector[0] == "R"
      self.coordinates_vector = self.coordinates_vector.gsub(',0','|').gsub(',',' ').gsub('|', ' , ').chop.chop.chop.gsub("R ", '')
    end
  end
end

app/controllers/admin/paths_controller.rb
class Admin::PathsController < ApplicationController
  layout 'admin'
  
  before_filter :authenticate_user!
  before_filter :find_path, only: [:update, :destroy]
  
  def update
    if @path.update_attributes(path_params)
      flash[:notice] = I18n.t('paths.update.success')
    else
      flash[:alert] = I18n.t('paths.update.failure')
    end
    
    redirect_to trips_admin_path(params[:path][:trip_id])
  end
  
  def create
    @path = Path.create(path_params)
    if @path.save
      PathTrip.create(path_id: @path.id, trip_id: params[:path][:trip_id])
      flash[:notice] = I18n.t('paths.create.success')
    else
      flash[:alert] = I18n.t('paths.create.failure')
    end
    
    redirect_to trips_admin_path(params[:path][:trip_id])
  end
  
  def destroy
    if @path.destroy
      flash[:notice] = I18n.t('paths.destroy.success')
    else
      flash[:alert] = I18n.t('paths.destroy.failure')
    end
    redirect_to :back
  end
  
  protected
  
  def find_path
    @path = Path.find(params[:id])
  end
  
  def path_params
     params[:path].permit(:name, :details, :thickness, :coordinates_vector, :color)
  end
end

app/views/admin/paths/_list.html.erb
<ul class="actions">
	<li><b>Trazos</b></li>
	<li><%= link_to 'Nuevo', 'javascript:void(0);', "data-form" => "new-path", :id => "new-path-field", :class => "highlighted edit-field" %></li> 
</ul>

<%= render 'admin/paths/new' %>

<div class="table">
	<div class="section">Trazos no asignados a este recorrido (<%= @trip_unassigned_paths.count %>)</div>
	<% @trip_unassigned_paths.each do |path| %>
		<%= render partial: 'admin/paths/path', object: path, locals: { assignable: true } %>
	<% end %>
	<div class="highlighted">
		<div class="section highlighted">Trazos asignados a este recorrido (<%= @trip_assigned_paths.count %>)</div>
		<% @trip_assigned_paths.each do |path| %>
			<%= render partial: 'admin/paths/path', object: path, locals: { assignable: false } %>
		<% end %>
	</div>
</div>

app/views/admin/paths/_new.html.erb
<div class="fieldset" id="new-path-form">
	<p class="main-title">Nuevo Path</p>
	<%= form_for Path.new, url: paths_admin_path do |f| %>
		<%= f.text_field :name, :class => 'input', placeholder: 'Nombre' %>
		<%= f.text_field :details, :class => 'input', placeholder: 'Detalles' %>
		<%= f.text_field :thickness, :class => 'input', placeholder: 'Thickness' %>
		<%= f.text_field :color, :class => 'input', placeholder: 'Color' %>
		<%= f.text_field :coordinates_vector, :class => 'input', placeholder: 'Vector' %>
		<%= f.hidden_field :trip_id, :value => @trip.id %>
		<div class="submit">
			<%= link_to 'Cancelar', 'javascript:void(0)', :class => 'hide-field', 'data-form' => "new-path" %> <%= f.submit 'Guardar cambios' %>
		</div>
	<% end %>
</div>

app/views/admin/paths/_path.html.erb
<div class="row path hoverable">
	<p class="title"><%= path.name %></p>
	<p class="actions">
		<% if assignable %>
			<%= link_to 'Ligar', path_trips_admin_path(path, @trip.id), :method => :post %> 
		<% else %>
			<%= link_to 'Desligar', path_trips_admin_delete_path(path, @trip.id), :method => :delete %> 
		<% end %>
		<%= link_to 'Editar', 'javascript:void(0);', :class => "edit-field map-toggle", :id => "path-#{path.id}-field", "data-form" => "path-#{path.id}" %> 
		<%= link_to 'Eliminar', paths_admin_delete_path(path), :method => :delete, :confirm => "¿Deseas eliminar este recorrido?" %> 
	</p>
</div>
<div class="fieldset" id="path-<%= path.id %>-form">
	<p class="main-title">Editando <%= path.name %></p>
	<%= form_for path, url: paths_admin_update_path(path), :method => :put do |f| %>
		<%= f.text_field :name, :class => 'input', placeholder: 'Nombre' %>
		<%= f.text_field :details, :class => 'input', placeholder: 'Detalles' %>
		<%= f.text_field :thickness, :class => 'input', placeholder: 'Thickness' %>
		<div style="background-color: #<%= path.color %>">
			<%= f.text_field :color, :class => 'input', placeholder: 'Color' %>
		</div>
		<%= f.text_field :coordinates_vector, :class => 'input', placeholder: 'Vector' %>
		<%= f.hidden_field :trip_id, :value => @trip.id %>
		<div class="map" id="path-<%= path.id %>-on-map"></div>
		<div class="submit">
			<%= link_to 'Cancelar', 'javascript:void(0)', :class => 'hide-field', 'data-form' => "path-#{path.id}" %> 
			<%= f.submit 'Guardar cambios' %>
		</div>
		

	<% end %>
</div>