config/routes.rb
HoopMan::Application.routes.draw do
  root 'welcome#index'
  
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  namespace :api do
    get '/inventory/trips' => 'trips#inventory'
    get '/inventory/light/trips' => 'trips#inventory', defaults: { publishing_mode: :lite }
    get '/inventory/staging/trips' => 'trips#inventory', defaults: { publishing_mode: :staging }
    
    get '/trips/:id' => 'trips#show'
    
    get '/inventory/images' => 'images#inventory'
    get '/inventory/trashes' => 'trashes#inventory'
  end

  get '/trips-admin' => 'admin/trips#index'
  get '/trips-admin/:id' => 'admin/trips#show', as: 'trips_admin'
  put '/trips-admin/:id' => 'admin/trips#update', as: 'trips_admin_update'
  get '/trips-admin/:id/edit' => 'admin/trips#edit', as: 'trips_admin_edit'
  get '/trips-admin/:id/duplicate' => 'admin/trips#duplicate', as: 'duplicate_trips_admin'
  delete '/trips-admin/:id' => 'admin/trips#destroy', as: 'delete_trips_admin'
  delete '/trips-admin/:id/hard_destroy' => 'admin/trips#hard_destroy', as: 'delete_hard_trips_admin'
  
  put '/users-admin/:id' => 'admin/users#update', as: 'users_admin_update'
  put '/images-admin/:id' => 'admin/images#update', as: 'images_admin_update'

  # Routes for paths
  put '/paths-admin/:id' => 'admin/paths#update', as: 'paths_admin_update'
  post '/paths-admin' => 'admin/paths#create', as: 'paths_admin'
  delete '/paths-admin/:id' => 'admin/paths#destroy', as: 'paths_admin_delete'
  
  # Routes for path-trips
  delete '/path_trips-admin/:path_id/:trip_id' => 'admin/path_trips#destroy', as: 'path_trips_admin_delete'
  post '/path_trips-admin/:path_id/:trip_id' => 'admin/path_trips#create', as: 'path_trips_admin'
  
  # Routes for pois
  get '/pois-admin/:id' => 'admin/pois#show', as: 'pois_admin'
  put '/pois-admin/:id' => 'admin/pois#update', as: 'pois_admin_update'
  delete '/pois-admin/:id' => 'admin/pois#destroy', as: 'pois_admin_delete'
  
  # Routes for poi-trips
  delete '/poi_trips-admin/:poi_id/:trip_id' => 'admin/poi_trips#destroy', as: 'poi_trips_admin_delete'
  post '/poi_trips-admin/:poi_id/:trip_id' => 'admin/poi_trips#create', as: 'poi_trips_admin'

  # Routes for contents
  post '/contents-admin' => 'admin/contents#create', as: 'contents_admin'
  delete '/contents-admin/:id' => 'admin/contents#destroy', as: 'contents_admin_delete'
  put '/contents-admin/:id' => 'admin/contents#update', as: 'contents_admin_update'
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :contentable, polymorphic: true, :inverse_of => :contents
  belongs_to :image
  
  after_save      :update_trip_checksum
  after_destroy   :update_trip_checksum
  
  validates :order, presence: true
  
  scope :staged_trips, -> { Content.joins("INNER JOIN trips ON contents.contentable_id = trips.id").where("contents.contentable_type = 'Trip' AND trips.staging = TRUE") }
  scope :staged_pois, -> { Content.joins("INNER JOIN pois ON contents.contentable_id = pois.id").where("contents.contentable_type = 'Poi' AND pois.staging = TRUE") }
  
  rails_admin do
    edit do
      include_all_fields
      exclude_fields :created_at, :updated_at, :trip_id
      
      field :html_string, :code_mirror
    end

    list do
      scopes [:staged_trips, :staged_pois, nil]
      field :id
      field :lang
      field :kind
      field :order_in_contentable do
        sortable :order
      end
    end
  end
  
  def lang
    contentable.blank? ? nil : contentable.lang
  end
  
  def order_in_contentable
    title = contentable.blank? ? nil : contentable.title
    "#{order} : #{contentable_type} - #{title}"
  end
  
  def kind_enum
    Content.kinds
  end
  
  def self.kinds
    ["route_controls", "paragraph", "legend", "photograph", "poi_table", "webview"]
  end
  
  def route_controls?
    self.kind == kind_enum[0]
  end
  
  def paragraph?
    self.kind == kind_enum[1]
  end
  
  def legend?
    self.kind == kind_enum[2]
  end
  
  def photograph?
    self.kind == kind_enum[3]
  end
  
  def poi_table?
    self.kind == kind_enum[4]
  end
  
  def webview?
    self.kind == kind_enum[5]
  end
  
  def full_name
    self.kind
  end
  
  protected 
  def update_trip_checksum
    (contentable.update_checksum && contentable.save) if(contentable_type == Trip.to_s)
    contentable.update_trips if(contentable_type == Poi.to_s)
  end
end

app/controllers/admin/contents_controller.rb
class Admin::ContentsController < ApplicationController
  layout 'admin'
  
  before_filter :find_trip, only: [:show, :edit, :update]
  before_filter :authenticate_user!
  
  def create
  end
  
end

app/views/admin/contents/_content.html.erb
<div class="row content hoverable content-<%= content.id %>">
	<% if content.route_controls? %>
		<div class="conceptual-content">
			<p>Controles de la ruta - <i><%= content.kind.upcase %></i></p>
		</div>
	<% elsif content.paragraph? %>
		<div class="paragraph">
			<p><%= content.content %> - <i><%= content.kind.upcase %></i></p>
		</div>
	<% elsif content.legend? %>
		<div class="legend">
			<p><%= content.title %> - <i><%= content.kind.upcase %></i></p>
		</div>
	<% elsif content.photograph? %>
		<div class="photograph">
			<p><%= content.image.name %> - <i><%= content.kind.upcase %></i></p>
		</div>
	<% elsif content.poi_table? %>
		<div class="conceptual-content">
			<p><%= content.table_title %> - <i><%= content.kind.upcase %></i></p>
		</div>
	<% elsif content.webview? %>
		<div class="webview">
			<p><%= content.html_string.safe! %> - <i><%= content.kind.upcase %></i></p>
		</div>
	<% end %>
	<p class="actions">
		<%= link_to 'Editar', 'javascript:void(0);', :class => "edit-field", :id => "content-#{content.id}-field", "data-form" => "content-#{content.id}" %> 
		<%= link_to 'Eliminar', contents_admin_delete_path(content), :method => :delete, :confirm => "¿Deseas eliminar este contenido?" %> 
	</p>
</div>
<div class="fieldset" id="content-<%= content.id %>-form">
	<p class="main-title">Editando <%= content.full_name %></p>
	<%= form_for content, url: contents_admin_update_path(content), :method => :put do |f| %>
		
		<p>Tipo de contenido <%= f.select :kind, Content.kinds %></p>

		<p><%= f.text_field :order, placeholder: 'Orden' %></p>
		
		<p><%= f.text_area :content, placeholder: "Contenido del párrafo", cols: 70, rows: 4 %></p>
		
		<p><%= f.text_area :title, placeholder: "Titulo" %></p>
		<p><%= f.text_area :subtitle, placeholder: "Subtitulo" %></p>
		<p><%= f.text_area :details, placeholder: "Detalles", cols: 70, rows: 4 %></p>
		
		
		<%= f.hidden_field :commentable_id, value: owner_object.id %>
		<%= f.hidden_field :commentable_type, value: owner_object_type %>
		
		<div class="submit">
			<%= link_to 'Cancelar', 'javascript:void(0)', :class => 'hide-field', 'data-form' => "content-#{content.id}" %> 
			<%= f.submit 'Guardar cambios' %>
		</div>
		

	<% end %>
</div>

app/views/admin/contents/_list.html.erb
<ul class="actions">
	<li><b>Contenidos</b></li>
	<li><%= link_to 'Nuevo', 'javascript:void(0);', "data-form" => "new-content", :id => "new-content-field", :class => "highlighted edit-field" %></li> 
</ul>

<%= render partial: 'admin/contents/new', locals: { owner_object_type: owner_object_type, owner_object: owner_object } %>

<div class="table">
	<% owner_object.contents.order(:order).each do |content| %>
		<p><%= render partial: 'admin/contents/content', object: content, locals: { owner_object: owner_object, owner_object_type: owner_object_type } %></p>
	<% end %>
</div>

app/views/admin/contents/_new.html.erb
<div class="fieldset" id="new-content-form">
	<p class="main-title">Nuevo Contenido</p>
	<%= form_for Content.new, url: contents_admin_path do |f| %>

		<%= f.hidden_field owner_object_type.to_s.concat('_id'), :value => owner_object.id %>
		<div class="submit">
			<%= link_to 'Cancelar', 'javascript:void(0)', :class => 'hide-field', 'data-form' => "new-content" %> <%= f.submit 'Guardar cambios' %>
		</div>
	<% end %>
</div>