config/routes.rb
HoopMan::Application.routes.draw do
  root 'welcome#index'
  
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  namespace :api do
    get '/inventory/trips' => 'trips#inventory'
    get '/inventory/light/trips' => 'trips#inventory', defaults: { publishing_mode: :lite }
    get '/inventory/staging/trips' => 'trips#inventory', defaults: { publishing_mode: :staging }
    
    get '/trips/:id' => 'trips#show'
    
    get '/inventory/images' => 'images#inventory'
    get '/inventory/trashes' => 'trashes#inventory'
  end

  get '/trips-admin' => 'admin/trips#index'
  get '/trips-admin/:id' => 'admin/trips#show', as: 'trips_admin'
  put '/trips-admin/:id' => 'admin/trips#update', as: 'trips_admin_update'
  get '/trips-admin/:id/edit' => 'admin/trips#edit', as: 'trips_admin_edit'
  get '/trips-admin/:id/duplicate' => 'admin/trips#duplicate', as: 'duplicate_trips_admin'
  delete '/trips-admin/:id' => 'admin/trips#destroy', as: 'delete_trips_admin'
  delete '/trips-admin/:id/hard_destroy' => 'admin/trips#hard_destroy', as: 'delete_hard_trips_admin'
  
  put '/users-admin/:id' => 'admin/users#update', as: 'users_admin_update'
  put '/images-admin/:id' => 'admin/images#update', as: 'images_admin_update'

  # Routes for paths
  put '/paths-admin/:id' => 'admin/paths#update', as: 'paths_admin_update'
  post '/paths-admin' => 'admin/paths#create', as: 'paths_admin'
  delete '/paths-admin/:id' => 'admin/paths#destroy', as: 'paths_admin_delete'
  
  # Routes for path-trips
  delete '/path_trips-admin/:path_id/:trip_id' => 'admin/path_trips#destroy', as: 'path_trips_admin_delete'
  post '/path_trips-admin/:path_id/:trip_id' => 'admin/path_trips#create', as: 'path_trips_admin'
  
  # Routes for pois
  get '/pois-admin/:id' => 'admin/pois#show', as: 'pois_admin'
  put '/pois-admin/:id' => 'admin/pois#update', as: 'pois_admin_update'
  delete '/pois-admin/:id' => 'admin/pois#destroy', as: 'pois_admin_delete'
  
  # Routes for poi-trips
  delete '/poi_trips-admin/:poi_id/:trip_id' => 'admin/poi_trips#destroy', as: 'poi_trips_admin_delete'
  post '/poi_trips-admin/:poi_id/:trip_id' => 'admin/poi_trips#create', as: 'poi_trips_admin'

  # Routes for contents
  post '/contents-admin' => 'admin/contents#create', as: 'contents_admin'
  delete '/contents-admin/:id' => 'admin/contents#destroy', as: 'contents_admin_delete'
  put '/contents-admin/:id' => 'admin/contents#update', as: 'contents_admin_update'
end

app/models/trip.rb
#encoding: utf-8
class Trip < ActiveRecord::Base  
  has_and_belongs_to_many :paths, class_name: "Path", join_table: :path_trips
  has_and_belongs_to_many :pois, class_name: "Poi", join_table: :poi_trips
  
  has_many :contents, as: :contentable, inverse_of: :contentable, dependent: :destroy
  
  belongs_to :main_image, class_name: 'Image', foreign_key: 'main_image_id'
  belongs_to :background_image, class_name: 'Image', foreign_key: 'background_image_id'
  belongs_to :user
  belongs_to :trip_resource
  
  before_save :update_checksum
  before_validation :update_coordinates
  
  validates :trip_resource, presence: true
  
  validates :distance, :title, :details, :complexity, :background_image, :main_image, :origin_lat, :origin_lon, :final_lat, :final_lon, presence: true
  
  attr_accessor :origin_lat, :origin_lon, :final_lon, :final_lat
  
  scope :staged, -> { where(staging: true) }
  
  rails_admin do    
       
    edit do
      include_all_fields
      exclude_fields :created_at, :updated_at, :checksum
            
      field :origin_lat
      field :origin_lon
      field :final_lat
      field :final_lon
    end
    
    list do
      scopes [:staged, nil]  
      field :lang
      field :full_name
      field :trip_resource
      field :available
      field :staging
      field :published_on_lite_version
    end
  end
  
  def self.find_all_with(publishing_mode)
    # Shows all staging trips which are either on the lite version and on the pro version
    if(publishing_mode == :staging)
      all.order(updated_at: :desc).order(available: :desc).where(:staging => true)
    # Shows all trips on lite which are not staging
    elsif(publishing_mode == :lite)
      all.order(updated_at: :desc).order(available: :desc).where(:published_on_lite_version => true, :staging => false)
    # Shows all trips on pro which are not staging
    else
      all.order(updated_at: :desc).order(available: :desc).where(:staging => false)
    end
  end
  
  def self.find_trip_with_id(id)
    find(id)
    
    rescue ActiveRecord::RecordNotFound
      return nil
  end
  
  def duplicate
    trip=self.dup
    trip.save
    
    self.paths.each do |path|
      new_path=path.dup
      new_path.save
      PathTrip.create(path: new_path, trip: trip)
    end
    
    self.pois.each do |poi|
      new_poi=poi.duplicate_with_children_and_save
      PoiTrip.create(poi: new_poi, trip: trip)
    end
    
    self.contents.each do |content|
      new_content=content.dup
      new_content.contentable_id = trip.id
      new_content.save
    end
    
    trip
  end
  
  def hard_destroy
    self.paths.each do |path|
      PathTrip.where(path_id: path.id, trip_id: self.id).destroy_all
      path.destroy
    end
    
    self.pois.each do |poi|
      PoiTrip.where(poi_id: poi.id, trip_id: self.id).destroy_all
      poi.destroy
    end
    
    self.destroy
  end
  
  def origin_lat
    return @origin_lat unless @origin_lat.nil?
    origin_coordinate.lat unless origin_coordinate.nil?
  end
  
  def origin_lon
    return @origin_lon unless @origin_lon.nil?
    origin_coordinate.lon unless origin_coordinate.nil?
  end
  
  def final_lat
    return @final_lat unless @final_lat.nil?
    end_coordinate.lat unless end_coordinate.nil?
  end
  
  def final_lon
    return @final_lon unless @final_lon.nil?
    end_coordinate.lon unless end_coordinate.nil?
  end
      
  def self.complexity_enum_alternate
    {
      es: ["Difícil", "Media", "Fácil"], 
      en: ["Hard", "Medium", "Easy"]
    }
  end   
  
  def self.complexity_enum
    ["Difícil", "Media", "Fácil", "Hard", "Medium", "Easy"]
  end 
      
  def self.lang_enum
    ["es", "en"]
  end
  
  def name
    full_name
  end
  
  def full_name
    "#{title} - #{lang}"
  end
  
  def update_checksum
    self.precompiled_json = TripSerializer.new(self).to_json
    self.checksum = Digest::SHA256.hexdigest(self.precompiled_json) 
  end
  
  protected
  def update_coordinates
    self.origin_coordinate = "POINT(#{self.origin_lon.to_f} #{self.origin_lat.to_f})"
    self.end_coordinate = "POINT(#{self.final_lon.to_f} #{self.final_lat.to_f})"
  end
end

app/controllers/admin/trips_controller.rb
class Admin::TripsController < ApplicationController
  layout 'admin'
  
  before_filter :find_trip, only: [:show, :edit, :update]
  before_filter :authenticate_user!
  
  def index
    @trip_resources = TripResource.all
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @trip.update_attributes(trip_params)
      flash[:notice] = I18n.t('trips.update.success')
    else
      flash[:alert] = I18n.t('trips.update.failure')
    end
    redirect_to trips_admin_path(@trip)
  end
  
  def duplicate
    @trip = Trip.find(params[:id])
    @trip.duplicate
    redirect_to :back
  end
  
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to :back
  end
  
  def hard_destroy
    @trip = Trip.find(params[:id])
    @trip.hard_destroy
    redirect_to :back
  end
  
  protected
  
  def trip_params
     params[:trip].permit(:title, :details, :cost, :lang, :complexity, :origin_lon, :origin_lat, :final_lat, :final_lon, :published_on_lite_version, :staging, :available, :distance)
  end
    
  def find_trip
    @trip = Trip.find(params[:id])
    @trip_assigned_paths = @trip.paths
    @trip_unassigned_paths = Path.all-@trip_assigned_paths
    
    @trip_assigned_pois = @trip.pois
    @trip_unassigned_pois = Poi.all-@trip_assigned_pois
  end
end

app/controllers/api/trips_controller.rb
class Api::TripsController < ActionController::Base
  skip_before_filter :verify_authenticity_token
  
  respond_to :json
  
  def show
    @trip = Trip.find_trip_with_id(params[:id])
    
    if @trip.nil?
      respond_with(@trip, :serializer => TripSerializer, :status => :not_found)
    else
      render json: @trip.precompiled_json
    end
  end
  
  def inventory
    @trips = Trip.find_all_with(params[:publishing_mode])
    respond_with(@trips, :each_serializer => TripInventorySerializer)
  end
end

app/views/admin/trips/edit.html.erb
<h4>Editando <%= @trip.title %></h4>

<%= form_for @trip, url: trips_admin_update_path(@trip), method: 'put' do |t| %>
	<%= t.label :lang %>
	<%= t.text_field :lang %>
	<br/>
	<%= t.label :title %>
	<%= t.text_field :title %>
	<br/>
	<%= t.label :details %>
	<%= t.text_area :details %>
	<br/>
	<%= t.label :cost %>
	<%= t.text_field :cost %>
	<br/>
	<%= t.submit %>
<% end %>

app/views/admin/trips/index.html.erb
<h2>Recorridos</h2>

<%= link_to 'Añadir Categoría de Recorrido', 'admin/trip_resource/new' %>

<% @trip_resources.each do |trip_resource| %>
	<div id="trip-<%= trip_resource.id %>" class="card">
		<div class="header">
			<p class="title"><b><%= trip_resource.identifier %></b></p>		
		</div>
		<% trip_resource.trips.each do |trip| %>
			<ul class="actions">
				<li><b><%= link_to "#{trip.title} - #{trip.lang}", trips_admin_path(trip) %></b></li>
				<li><%= link_to "Clonar", duplicate_trips_admin_path(trip), confirm: '¿Deseas clonar este recorrido?'  %></li>
				<li><%= link_to "Eliminar", delete_trips_admin_path(trip), :method => :delete, confirm: '¿Deseas eliminar este recorrido?' %></li>
				<li><%= link_to "Eliminar Completamente", delete_hard_trips_admin_path(trip), :method => :delete, confirm: '¿Deseas eliminar completamente este recorrido?' %></li>
			</ul>
		<% end %>
	</div>
<% end %>

app/views/admin/trips/show.html.erb
<%= render partial: 'admin/shared/notifications' %>

<div class="centered">
	<h2>Detalles del recorrido</h2>
</div>

<div class="card">
	<ul class="actions">
		<li><%= link_to 'Atrás', '/trips-admin' %></li>
	</ul>
	
	<div class="header">
		<div class="title half-size">
			<h3 id="title-and-lang-field" class="hoverable edit-field" data-form="title-and-lang"><%= @trip.title %> - <%= @trip.lang %></h3> 
			<%= render 'admin/trips/fields/title_and_lang' %>
		</div>
		<div class="creator half-size">
			<p id="creator-info-field" class="hoverable edit-field" data-form="creator-info"><b>por </b> <%= @trip.user.full_name %></p>
			<%= render 'admin/trips/fields/creator_info' %>
		</div>
	</div>
	
	<div class="sub-header">
		<div id="map" class="for-trip"></div>
		<div class="coordinates">
			<div class="toggler">
				<%= link_to 'Editar coordenadas', 'javascript:void(0)', :class => 'edit-field', id: 'coordinates-field', 'data-form' => 'coordinates' %>
			</div>
			<%= render 'admin/trips/fields/coordinates' %>
		</div>
	</div>
	
	<div id="details-field" class="details hoverable edit-field" data-form="details"><%= @trip.details %></div>
	<%= render 'admin/trips/fields/details' %>

	<div class="table">
		<div class="section">Características</div>
		<div id="distance-field" class="row hoverable edit-field" data-form="distance">
			<div class="section-title">Distancia</div>
			<div class="section-details"><%= @trip.distance %></div>
		</div>
		<%= render 'admin/trips/fields/distance' %>
		
		<div id="complexity-field" class="row hoverable edit-field" data-form="complexity">
			<div class="section-title">Complejidad</div>
			<div class="section-details"><%= @trip.complexity %></div>
		</div>
		<%= render 'admin/trips/fields/complexity' %>
		
		<div id="background-field" class="row hoverable edit-field" data-form="background">
			<div class="section-title">Fondo para el recorrido</div>
			<div class="section-details"><%= @trip.background_image.name %></div>
		</div>
		<%= render 'admin/trips/fields/background' %>
		
		<div id="main-image-field" class="row hoverable edit-field" data-form="main-image">
			<div class="section-title">Imagen de Portada</div>
			<div class="section-details"><%= @trip.main_image.name %></div>
		</div>
		<%= render 'admin/trips/fields/main_image' %>
		
		<div class="section">Estado en AppStore</div>
		
		<div id="cost-field" class="row hoverable edit-field" data-form="cost">
			<div class="section-title">Costo (Descontinuado)</div>
			<div class="section-details"><%= @trip.cost %> MXN</div>
		</div>
		<%= render 'admin/trips/fields/cost' %>
		
		<div id="published-field" class="row hoverable edit-field" data-form="published">
			<div class="section-title">¿Es visible en la app?</div>
			<div class="section-details"><%=  t('options')[@trip.staging] %></div>
		</div>
		<%= render 'admin/trips/fields/published' %>
		
		<div id="lite-version-field" class="row hoverable edit-field" data-form="lite-version">
			<div class="section-title">Disponible en version lite</div>
			<div class="section-details"><%= t('options')[@trip.published_on_lite_version] %></div>
		</div>
		<%= render 'admin/trips/fields/lite_version' %>
		
		<div id="available-field" class="row hoverable edit-field" data-form="available">
			<div class="section-title">Publicada y Disponible</div>
			<div class="section-details"><%= t('options')[@trip.available] %></div>
		</div>
		<%= render 'admin/trips/fields/available' %>
		
	</div>
</div>

<div class="card">
	<%= render partial: 'admin/contents/list', locals: { owner_object: @trip, owner_object_type: :trip } %>
</div>

<div class="card">
	<%= render partial: 'admin/paths/list', locals: { trip: @trip } %>	
</div>

<div class="card">
	<%= render partial: 'admin/pois/list', locals: { trip: @trip } %>
</div>